set -e
true
true
/usr/local/bin/spades-hammer /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/corrected/configs/config.info
/usr/bin/python /usr/local/share/spades/spades_pipeline/scripts/compress_all.py --input_file /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/corrected/corrected.yaml --ext_python_modules_home /usr/local/share/spades --max_threads 16 --output_dir /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/corrected --gzip_output
true
true
/usr/local/bin/spades-core /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/K21/configs/config.info
/usr/local/bin/spades-core /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/K33/configs/config.info
/usr/local/bin/spades-core /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/K55/configs/config.info
/usr/local/bin/spades-core /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/K77/configs/config.info
/usr/bin/python /usr/local/share/spades/spades_pipeline/scripts/copy_files.py /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/K77/before_rr.fasta /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/before_rr.fasta /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/K77/assembly_graph_after_simplification.gfa /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/assembly_graph_after_simplification.gfa /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/K77/final_contigs.fasta /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/contigs.fasta /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/K77/first_pe_contigs.fasta /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/first_pe_contigs.fasta /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/K77/strain_graph.gfa /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/strain_graph.gfa /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/K77/scaffolds.fasta /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/scaffolds.fasta /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/K77/scaffolds.paths /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/scaffolds.paths /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/K77/assembly_graph_with_scaffolds.gfa /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/assembly_graph_with_scaffolds.gfa /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/K77/assembly_graph.fastg /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/assembly_graph.fastg /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/K77/final_contigs.paths /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/contigs.paths
true
/usr/bin/python /usr/local/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/scaffolds.fasta --misc_dir /home/aesparza2/adridirectory/AdriPipeline/AdrianaPipeline/ASSEMBLY/misc --threshold_for_breaking_scaffolds 3
true
